name: Generate Catalog PR

on:
  workflow_dispatch:
    inputs:
      appName:
        description: "NR1 Nerdpack Name"
        required: true
      version:
        description: "Version to update"
        required: true
      ref:
        description: "Commit SHA to update the submodule to"
        required: true
      user:
        description: "User who initiated the deployment"
        required: true

env:
  GIT_AUTHOR_NAME: "nr-opensource-bot"
  GIT_AUTHOR_EMAIL: "opensource+bot@newrelic.com"
  GIT_COMMITTER_NAME: "nr-opensource-bot"
  GIT_COMMITTER_EMAIL: "opensource+bot@newrelic.com"

jobs:
  job-check-workflow-dispatch-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "App Name: ${{ github.event.inputs.appName }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "ref: ${{ github.event.inputs.ref }}"
          echo "User: ${{ github.event.inputs.user }}"

  job-create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      # Create a new branch, Update submodule to the input ref and commit
      - name: Update submodule
        run: |
          git config user.email "${{ env.GIT_AUTHOR_EMAIL }}"
          git config user.name "${{ env.GIT_AUTHOR_NAME }}"

          # Create branch
          # git checkout -b ${{ github.event.inputs.appName }}/${{ github.event.inputs.version }}

          # Update submodule
          cd apps/${{ github.event.inputs.appName }}
          git checkout ${{ github.event.inputs.ref }}
          cd ../..

          # Commit back to branch
          git add apps/${{ github.event.inputs.appName }}
          git commit -m 'feat: update ${{ github.event.inputs.appName }} to version ${{ github.event.inputs.version }}'
          echo "::set-output name=commit::true"

      # Open PR using this new branch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.OPENSOURCE_BOT_TOKEN}}
          commit-message: "Updating ${{ github.event.inputs.appName }} to ${{ github.event.inputs.version }}"
          committer: ${{ env.GIT_COMMITTER_NAME }} <${{ env.GIT_COMMITTER_EMAIL }}>
          author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          branch: ${{ github.event.inputs.appName }}/${{ github.event.inputs.version }}
          base: master
          title: "Updating ${{ github.event.inputs.appName }} to ${{ github.event.inputs.version }}"
          body: |
            Automated PR created by nr1-catalog deploy nerdlet. 

            Initiated by: @${{ github.event.inputs.user }}
          labels: |
            Automated PR
          assignees: |
            jbeveland27
          reviewers: |
            jbeveland27

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
