name: Check for Platform Deprecations in Apps

on:
  issues:
    types: [labeled,opened]

jobs:
  add-comment:
    if: github.event.label.name == 'deprecations'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Developer Enablement Team
          column: To do
          repo-token: ${{ secrets.OPENSOURCE_BOT_TOKEN }}
